### ISSUE TITLE
Demo页 js加载失败

### ISSUE THREAD

**Issue by 2foil** [SweetInk/Infinity-Gauntlet-demo#1]
- html2canvas.js
- jquery.min.js

Demo页的上面这两个js用的外链，被Chrome 拦截了，导致效果预览失败。

如图：

![blocked1](https://ws3.sinaimg.cn/large/006KRXz2ly1g2i4ieq83xj30ju0bggng.jpg)

![blocker2](https://wx2.sinaimg.cn/large/006KRXz2ly1g2i4i1lt71j31pa0a641f.jpg)

**Comment by SweetInk** [comment]
已修复
